// package lab6_Ex3

// import chisel3._
// import chisel3.util._
// import chiseltest._
// import org.scalatest._

// class Test_Two_Shot_Timer extends FreeSpec with ChiselScalatestTester{
//     "Test Two Shot Timer" in {
//         test(new Two_Shot_Timer) { c =>
//             c.io.reload.poke(1.B)
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
//             c.clock.step()
//             println(c.io.out_off.peek())
//             println(c.io.out_on.peek())
            

//         }
//     }
// }